# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c33e186e25f5dea51966db33521261f7fde9754e5c4d7b14c0fa198a25d77424231fd08dbcb2044431154fd6a998cfa4cd30d8c6d2ee5e3aabc1d9a4690402

test:
  secret_key_base: ca6394e8f29e4984a78df05b1b10bdb38cbeb605f0bf4498e86be74aefd874ce538cc29411412a914d6e775b20a6a88bf62949db5be4321c63d2480970f83fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
